language: python

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34

install:
  - pip install tox
  - pip install .
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

deploy:
  provider: pypi
  user: rax_cbd_dev
  password:
    secure: fzRZJnrx1ikbQpdJvPyqrR7dhXLLqQDf4BUKT/Sgr7oW+yHOXkkUgDzavMn/7/GzeNNJxeqi/tWFvjfmGo8rsFuqUV3GA6qD5BYCbwvGA5HIDrkKoagt5P01vqPK9W1Jl+ILs5ylCS5a/sn31ah42igCkFilSGk+IVVHk98zJ2za/JGg/x7tphosFEOrYbauSDANeeRDcfRvtWGFrlQGw7yqh4cTRFhqow4H8N1kq+MGRpVaNOo9DFVg/m0vTvqmi117ysGqn8lSUSMEyd9jLiWiDLYY06XrQohGZHa3oY8lpbCCX6KIkc2ri6vgh/8C9IbSlfHyfDx5WlO1PRnQB5YaMyGa4X/Nqf2lORG81mmllHZE76GSmWc3jXDl1XSOshi3bEDeZOAh+JTAWfWxKHbBq32ub5uH5NRjtXZfVi7JovBBXsjfryyizaFYfcmG/p1gZ66FbW7mlOMaJMCRudDSnWruOeuv7BqZ0Lx6TogNQ6+spZuHqoJqgLMrIbbeQS6yAOtA6+VjOr71uNGEl8v7bToq8yUIbG+2n2vOrGhTeaQQt1i9fZvD8t84GuC55eoW/kt7vSmlzqYdq3KpE0M+0/rKuBSu8A16iBNTlOc81y/End9+Y45h+HEnx1FNzoEXh88T9OpaaGwBuyjdpd0gTONVN7KNb1HFVI8TOL4=
  on:
    tags: true
    repo: rackerlabs/python-lavaclient
  distributions: "sdist bdist_wheel"

python:
  - "3.4"

script:
  - tox
